<?php
/*error_reporting(E_ALL);
ini_set('display_errors', '1');
/**
 * Implements hook_block_info().
 */
function dayscript_theme(){
	$hooks = array();
	$hooks[ 'indicadores_economicos' ] = array(
		'variables' => array( 'data' => array() ),
		'template'  => "templates/indicadores"
	);
	return $hooks;
}
function dayscript_block_info() {
	$blocks['indicadores_economicos'] = array(
		'info'  => 'indicadores economicos',
	);
	$blocks['indicadores_popup_confirmation'] = array(
		'info'  => 'indicadores economicos confirmacion popup',
	);
	return $blocks;
}
function dayscript_block_view($delta='') {
	$block = array();
	switch ($delta) {
		case 'indicadores_economicos':
			$block['subject'] = 'indicadores economicos';
			$block['content'] = theme( 'indicadores_economicos', array( 'data' => _getIndicadoresEconomicos() ) );
			break;
		case 'indicadores_popup_confirmation':
			$block['subject'] = 'indicadores economicos popup';
			$block['content'] =  _indicadoresEconomicosPopupConfirmation();
			break;
	}
	return $block;
}
function _getIndicadoresEconomicos() {
	$aditionalParameters = "DTF 90 Días,Euro,UVR,TRM";
	$url="http://190.27.201.2/autocontent/index.php?economy=DTF%2090%20D%C3%ADas,Euro,UVR,TRM&json=json&indicadores=ok";
	$data=file_get_contents($url);
	return $data;
}

function _indicadoresEconomicosPopupConfirmation(){
	if(isset($_GET['nid'])&&isset($_GET['sid'])){

		$nid = $_GET['nid'];
		$sid = $_GET['sid'];

		include_once(drupal_get_path('module', 'webform') .'/includes/webform.submissions.inc');
		$submission = webform_get_submission($nid, $sid);
		$query = new EntityFieldQuery();
		$entities = $query->entityCondition('entity_type', 'node')
			->propertyCondition('type', 'logo_portafolio')
			->propertyCondition('title',$submission->data[1][0], '=')
			->propertyCondition('status', 1)
			->execute();
		$node=array_keys($entities['node']);
		$node = node_load($node[0]);
		$node_view = node_view($node,$view_mode = 'full');
		$rendered_node = drupal_render($node_view);
		return "<div class='reveal-modal'><span class='close'>x</span>".$rendered_node."</div>";
	}
}
/**
 * Implements hook_form_alter().
 */
function dayscript_form_alter(&$form, &$form_state, $form_id)
{
	
	if($form_id == 'webform_client_form_23'){
		$query = new EntityFieldQuery();
		$entities = $query->entityCondition('entity_type', 'node')
			->propertyCondition('type', 'logo_portafolio')
			->fieldCondition('field_tipo_de_portafolio', 'tid', array('4'), '=')
			->propertyCondition('status', 1)
			->execute();
		$cont =0;
		$dataNid =array();
		foreach($query->ordered_results as $node_id){
			$data=node_load($node_id->entity_id);
			$dataNid[$data->title]=$data->title;
		}
		$form['submitted']['aseguradora']['#options'] = $dataNid;
	}

	if($form_id =="webform_client_form_42"){
		$term=explode('/',$_GET['q']);
		$taxonomy_term = taxonomy_term_load($term[2]);
		$query = new EntityFieldQuery();
		$entities = $query->entityCondition('entity_type', 'node')
			->propertyCondition('type', 'seguro')
			->fieldCondition('field_tipo_de_seguro', 'tid',$taxonomy_term->tid , '=')
			->propertyCondition('status', 1)
			->execute();
		$entities = array_keys($entities['node']);
		$nodes = entity_load('node',$entities);
		$data=array();
		foreach($nodes as $key=>$value){
			$data[$value->title] = ucfirst(strtolower($value->title));
		}
		$form['submitted']['producto']['#options'] = $data;  
	
	}

	if($form['#action'] == '/node/42/webform/components/7?destination=node/42/webform' && $form_id = "webform_component_edit_form" 
		&& $form['#node']->vid == '42') {
		dpm($form);
		$vocabulary=taxonomy_vocabulary_machine_name_load('productos');
		$data = entity_load('taxonomy_term', FALSE, array('vid' => $vocabulary->vid));		
		$options = "";
		foreach($data as $key => $term ){
			$options .= $term->name."|".$term->name."\n"; 
		}
		$form['extra']['items']['#default_value'] = $options;
	}

		
}





