<?php
error_reporting(E_ALL);
ini_set('display_errors', '1');
/**
 * Implements hook_block_info().
 */

	

	function dayscript_theme()
{
    $hooks = array();
    $hooks[ 'indicadores_economicos' ] = array(
        'variables' => array( 'data' => array() ),
        'template'  => "templates/indicadores"
    );
    return $hooks;
}


	function dayscript_block_info() {
	  $blocks['indicadores_economicos'] = array(
	    'info'  => 'indicadores economicos',
	  );
	  return $blocks;
	}

	function dayscript_block_view($delta='') {
	  $block = array();
	  switch ($delta) {
	  case 'indicadores_economicos':
	    $block['subject'] = 'indicadores economicos';
	    $block['content'] = theme( 'indicadores_economicos', array( 'data' => _getIndicadoresEconomicos() ) );
	    break;
	  }
	  return $block;
	}

	function _getIndicadoresEconomicos() {
  		
		$aditionalParameters = "DTF 90 Días,Euro,UVR,TRM";
		$url="http://190.27.201.2/autocontent/index.php?economy=DTF%2090%20D%C3%ADas,Euro,UVR,TRM&json=json&indicadores=ok";
		$data=file_get_contents($url);
  		
  		return $data;
	}


/**
 * Implements hook_form_alter().
 */

	function dayscript_form_alter(&$form, &$form_state, $form_id)
	{
	 	if($form_id == 'webform_client_form_23'){
	 		
	 		$query = new EntityFieldQuery();
			  $entities = $query->entityCondition('entity_type', 'node')
			  ->propertyCondition('type', 'logo_portafolio')
			  ->fieldCondition('field_tipo_de_portafolio', 'tid', array('4'), '=')
			  ->propertyCondition('status', 1)
			  ->execute();
			
			$cont =0;
			//dpm($query);
			//dpm($query->ordered_results[0]->entity_id);
			$dataNid =array();
			
			foreach($query->ordered_results as $node_id){
			   $data=node_load($node_id->entity_id);
			   $dataNid[$data->title]=$data->title;
			}

	 		$form['submitted']['aseguradora']['#options']= $dataNid;
	 		
	 		//dpm($form);
	 	}
  		
	}	

	function dayscript_submit($form,&$form_state){
		

	}